// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tutorial

import (
	"database/sql"
)

type User struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Username  sql.NullString
	Password  sql.NullString
	Language  sql.NullInt16
}
